C:\Users\chris\anaconda3\envs\marlo\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\chris\anaconda3\envs\marlo\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\chris\anaconda3\envs\marlo\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
2023-12-30 15:18:09.593899: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2023-12-30 15:18:11.479400: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2023-12-30 15:18:11.501730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:2b:00.0 name: NVIDIA GeForce RTX 4070 computeCapability: 8.9
coreClock: 2.505GHz coreCount: 46 deviceMemorySize: 11.99GiB deviceMemoryBandwidth: 469.43GiB/s
2023-12-30 15:18:11.501927: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2023-12-30 15:18:11.505082: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2023-12-30 15:18:11.505218: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2023-12-30 15:18:11.505332: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2023-12-30 15:18:11.508398: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2023-12-30 15:18:11.510054: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
GPUs [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2023-12-30 15:18:11.514231: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2023-12-30 15:18:11.514364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
C:\Users\chris\anaconda3\envs\marlo\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float64
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2023-12-30 15:18:11.896607: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-30 15:18:11.907108: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x164c77d06c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-12-30 15:18:11.907347: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-12-30 15:18:11.907725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:2b:00.0 name: NVIDIA GeForce RTX 4070 computeCapability: 8.9
coreClock: 2.505GHz coreCount: 46 deviceMemorySize: 11.99GiB deviceMemoryBandwidth: 469.43GiB/s
2023-12-30 15:18:11.907995: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2023-12-30 15:18:11.908126: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2023-12-30 15:18:11.908253: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2023-12-30 15:18:11.908373: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2023-12-30 15:18:11.908518: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2023-12-30 15:18:11.908662: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2023-12-30 15:18:11.908811: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2023-12-30 15:18:11.908971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2023-12-30 15:18:14.417652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-12-30 15:18:14.417760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2023-12-30 15:18:14.417821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2023-12-30 15:18:14.417991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10335 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 4070, pci bus id: 0000:2b:00.0, compute capability: 8.9)
2023-12-30 15:18:14.421517: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1651c328cd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-12-30 15:18:14.421879: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 4070, Compute Capability 8.9
WARNING:tensorflow:From C:\Users\chris\anaconda3\envs\marlo\lib\site-packages\tensorflow\python\keras\engine\training_v1.py:2070: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2023-12-30 15:18:19.430491: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
episode: 0/100, score: -117.40000100000003, average_score: -117.40000100000003, average_kills: 0, Win:False
episode: 1/100, score: -161.944005, average_score: -139.67200300000002, average_kills: 0, Win:False
episode: 2/100, score: -209.79999999999978, average_score: -163.04800199999994, average_kills: 0, Win:False
episode: 3/100, score: -151.90000100000012, average_score: -160.26100175, average_kills: 0, Win:False
episode: 4/100, score: -36.456012999999245, average_score: -135.50000399999985, average_kills: 0, Win:False
episode: 5/100, score: -95.72801700000011, average_score: -128.8713394999999, average_kills: 0, Win:False
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\malmo_agent.py", line 248, in __safe_start_mission
    self.malmo_agent.startMission(mission, self.client_pool, mission_record, role, expId)
malmo.MalmoPython.MissionException: Failed to find an available client for this mission - tried all the clients in the supplied client pool.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\main.py", line 459, in <module>
    agent.test()
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\main.py", line 433, in test
    state = self.env.reset()
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\gym_env.py", line 19, in reset
    self.agent.start_episode()
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\malmo_agent.py", line 66, in start_episode
    self.__safe_start_mission(self.mission, MalmoPython.MissionRecordSpec(), 0, experimentID)
  File "C:\Users\chris\Desktop\Ptixiaki\Projects\Fighting-Zombies-RL-PPO\malmo_agent.py", line 257, in __safe_start_mission
    time.sleep(2)
KeyboardInterrupt
